<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $homeContent = [
            'hero' => [
                'eyebrow' => 'Веб-студия',
                'title' => 'Создание сайтов и цифровых продуктов',
                'lead' => 'Разработка и сопровождение веб-проектов — важный шаг в развитии вашего бизнеса. Мы заботимся об имидже компании и не используем шаблонные решения низкого качества. Имидж — это долгосрочная инвестиция.',
            ],
            'stats' => [
                ['value' => '12+', 'label' => 'специалистов в команде'],
                ['value' => '8', 'label' => 'лет на рынке'],
                ['value' => '150+', 'label' => 'реализованных проектов'],
            ],
            'services' => [
                ['num' => '01', 'title' => 'Различные платформы', 'text' => 'Создание сайтов на Laravel, WordPress, 1C-Битрикс и других CMS с учётом задач бизнеса.'],
                ['num' => '02', 'title' => 'SEO и продвижение', 'text' => 'Оптимизация под Яндекс и Google. Вывод в ТОП-10 — стабильный поток клиентов и рост прибыли.'],
                ['num' => '03', 'title' => 'Интернет-магазины и порталы', 'text' => 'Каталоги, личные кабинеты, биллинг, интеграции с CRM, складом и платёжными системами.'],
                ['num' => '04', 'title' => 'Быстрый старт', 'text' => 'Запуск на базе проверенных решений за 1–2 недели — оптимально по срокам и бюджету.'],
                ['num' => '05', 'title' => 'Поддержка и развитие', 'text' => 'Доработка, раскрутка, SMM, техническое сопровождение действующих проектов.'],
            ],
            'cases' => [
                [
                    'tag' => 'Недвижимость',
                    'title' => 'Портал объектов',
                    'client' => 'Клиент: агентство недвижимости',
                    'points' => ['Каталог объектов по направлениям', 'Внутренний биллинг и платные пакеты', 'Автообновление объявлений для агентств'],
                    'result' => 'портал с посещаемостью до 30 тыс. пользователей в сутки.',
                ],
                [
                    'tag' => 'Финансы',
                    'title' => 'Корпоративный портал',
                    'client' => 'Клиент: страховая компания',
                    'points' => ['Калькулятор взносов и онлайн-оплата', 'Кабинеты клиента, агента и брокера', 'Конструктор виджетов для банков'],
                    'result' => 'единая платформа с разными уровнями доступа.',
                ],
                [
                    'tag' => 'Логистика',
                    'title' => 'Доставка и таможня',
                    'client' => 'Клиент: международная логистика',
                    'points' => ['Оформление доставки онлайн', 'Интеграция со складом и таможней', 'Расчёт пошлин и стоимости доставки'],
                    'result' => 'система до 500 одновременных подключений.',
                ],
            ],
            'benefits' => [
                ['title' => 'Договор и ТЗ', 'text' => 'Подписание технического задания даёт уверенность, что результат будет именно таким, как вы ожидаете.'],
                ['title' => 'Опыт 8+ лет', 'text' => 'Команда постоянно совершенствует навыки и осваивает новые технологии в веб-разработке.'],
                ['title' => '150+ клиентов', 'text' => 'Большинство заказчиков остаются с нами на сопровождение и развитие проектов.'],
                ['title' => 'Сроки', 'text' => '95% проектов запущены в срок или раньше оговорённой даты.'],
            ],
            'team' => [
                ['initial' => 'А', 'name' => 'Алексей', 'role' => 'Руководитель'],
                ['initial' => 'М', 'name' => 'Мария', 'role' => 'Project-менеджер'],
                ['initial' => 'Д', 'name' => 'Дмитрий', 'role' => 'PHP-разработчик'],
                ['initial' => 'Е', 'name' => 'Елена', 'role' => 'Frontend'],
                ['initial' => 'О', 'name' => 'Ольга', 'role' => 'Дизайнер'],
                ['initial' => 'И', 'name' => 'Игорь', 'role' => 'SEO-специалист'],
                ['initial' => 'К', 'name' => 'Кирилл', 'role' => 'Backend'],
                ['initial' => 'А', 'name' => 'Анна', 'role' => 'Аккаунт-менеджер'],
            ],
            'clients' => ['GoHome', 'PriorLife', 'ProStore', 'Микро Лизинг', 'Fine Adviser', 'USAPostLine', 'Айчына', 'Белджи', 'Невестам', 'Teploluxe', 'Haval', 'Йетти'],
            'departments' => [
                ['icon' => '📈', 'title' => 'SEO и маркетинг', 'text' => 'Продвижение в ТОП поисковых систем и удержание позиций надолго.'],
                ['icon' => '⚙️', 'title' => 'Разработка', 'text' => 'Воплощение проектов с нужным функционалом — стабильно и без сбоев.'],
                ['icon' => '📱', 'title' => 'Вёрстка', 'text' => 'Удобство во всех браузерах и на мобильных устройствах.'],
                ['icon' => '🎯', 'title' => 'Менеджмент', 'text' => 'Координация команды, сроки и выполнение поставленных задач.'],
                ['icon' => '🎨', 'title' => 'Дизайн', 'text' => 'Визуал, который запоминается и удобен для посетителей сайта.'],
            ],
        ];

        $pricingContent = [
            'intro' => [
                'eyebrow' => 'Стоимость',
                'lead' => 'Прозрачные тарифы на разработку сайтов. Финальная цена зависит от объёма работ и согласовывается после брифа.',
            ],
            'plans' => [
                [
                    'name' => 'Старт',
                    'price' => '890',
                    'currency' => 'BYN',
                    'period' => 'от',
                    'description' => 'Лендинг или сайт-визитка для быстрого запуска.',
                    'featured' => false,
                    'features' => [
                        'До 5 страниц',
                        'Адаптивная вёрстка',
                        'Базовая SEO-настройка',
                        'Форма обратной связи',
                        '1 месяц поддержки',
                    ],
                    'cta' => 'Заказать',
                ],
                [
                    'name' => 'Бизнес',
                    'price' => '2 490',
                    'currency' => 'BYN',
                    'period' => 'от',
                    'description' => 'Корпоративный сайт с CMS и расширенным функционалом.',
                    'featured' => true,
                    'badge' => 'Популярный',
                    'features' => [
                        'До 15 страниц',
                        'Админ-панель (CMS)',
                        'Интеграция аналитики',
                        'SEO-оптимизация',
                        '3 месяца поддержки',
                    ],
                    'cta' => 'Обсудить проект',
                ],
                [
                    'name' => 'Портал',
                    'price' => '5 900',
                    'currency' => 'BYN',
                    'period' => 'от',
                    'description' => 'Интернет-магазин, портал или CRM-решение под ключ.',
                    'featured' => false,
                    'features' => [
                        'Индивидуальный дизайн',
                        'Личные кабинеты',
                        'Интеграции (CRM, оплата)',
                        'Нагрузочное тестирование',
                        '6 месяцев поддержки',
                    ],
                    'cta' => 'Получить смету',
                ],
            ],
            'extras' => [
                [
                    'title' => 'SEO-продвижение',
                    'text' => 'от 350 BYN/мес — аудит, семантика, контент, ссылки.',
                ],
                [
                    'title' => 'Техподдержка',
                    'text' => 'от 150 BYN/мес — обновления, резервные копии, мониторинг.',
                ],
                [
                    'title' => 'Доработки',
                    'text' => 'от 45 BYN/час — новые разделы, интеграции, дизайн.',
                ],
            ],
            'note' => 'Точная стоимость рассчитывается после обсуждения задач. Оставьте заявку — подготовим коммерческое предложение в течение 1–2 рабочих дней.',
        ];

        $pages = [
            [
                'slug' => 'home',
                'title' => 'Nexora — создание сайтов и веб-разработка',
                'description' => 'Nexora — разработка и сопровождение веб-проектов под ключ. Современные сайты, порталы и автоматизация бизнес-процессов.',
                'content' => $homeContent,
                'active' => true,
                'show_in_menu' => false,
                'menu_order' => 0,
                'menu_type' => 'route',
                'seo_title' => 'Nexora — создание сайтов и веб-разработка',
                'seo_description' => 'Nexora — разработка и сопровождение веб-проектов под ключ.',
            ],
            [
                'slug' => 'nav-services',
                'title' => 'Услуги',
                'description' => null,
                'content' => null,
                'active' => true,
                'show_in_menu' => true,
                'menu_order' => 10,
                'menu_label' => 'Услуги',
                'menu_type' => 'anchor',
                'menu_hash' => '#services',
            ],
            [
                'slug' => 'projects',
                'title' => 'Портфолио — Nexora',
                'description' => 'Портфолио Nexora: корпоративные сайты, интернет-магазины, порталы и CRM-решения.',
                'content' => null,
                'active' => true,
                'show_in_menu' => true,
                'show_in_footer' => true,
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 20,
                'footer_label' => 'Портфолио',
                'menu_order' => 20,
                'menu_label' => 'Портфолио',
                'menu_type' => 'route',
                'seo_title' => 'Портфолио — Nexora',
                'seo_description' => 'Портфолио Nexora: корпоративные сайты, интернет-магазины, порталы и CRM-решения.',
            ],
            [
                'slug' => 'news',
                'title' => 'Новости — Nexora',
                'description' => 'Новости студии Nexora: запуски проектов, обновления сервиса и события команды.',
                'content' => null,
                'active' => true,
                'show_in_menu' => true,
                'show_in_footer' => true,
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 30,
                'footer_label' => 'Новости',
                'menu_order' => 25,
                'menu_label' => 'Новости',
                'menu_type' => 'route',
                'seo_title' => 'Новости Nexora — веб-студия',
                'seo_description' => 'Актуальные новости Nexora о разработке сайтов и digital-проектах.',
            ],
            [
                'slug' => 'articles',
                'title' => 'Статьи — Nexora',
                'description' => 'Полезные материалы о создании сайтов, SEO и автоматизации бизнеса.',
                'content' => null,
                'active' => true,
                'show_in_menu' => true,
                'show_in_footer' => true,
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 40,
                'footer_label' => 'Статьи',
                'menu_order' => 26,
                'menu_label' => 'Статьи',
                'menu_type' => 'route',
                'seo_title' => 'Статьи о веб-разработке — Nexora',
                'seo_description' => 'Статьи Nexora: как выбрать подрядчика, SEO, CMS и сопровождение сайтов.',
            ],
            [
                'slug' => 'pricing',
                'title' => 'Цены — Nexora',
                'description' => 'Стоимость разработки сайтов, интернет-магазинов и порталов. Тарифы Nexora с прозрачным ценообразованием.',
                'content' => $pricingContent,
                'active' => true,
                'show_in_menu' => true,
                'show_in_footer' => true,
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 10,
                'footer_label' => 'Стоимость создания сайта',
                'menu_order' => 30,
                'menu_label' => 'Цены',
                'menu_type' => 'route',
                'seo_title' => 'Цены на разработку сайтов — Nexora',
                'seo_description' => 'Тарифы на создание сайтов, корпоративных порталов и интернет-магазинов. Стоимость от 890 BYN.',
            ],
            [
                'slug' => 'nav-team',
                'title' => 'Команда',
                'description' => null,
                'content' => null,
                'active' => true,
                'show_in_menu' => true,
                'menu_order' => 40,
                'menu_label' => 'Команда',
                'menu_type' => 'anchor',
                'menu_hash' => '#team',
            ],
            [
                'slug' => 'nav-contact',
                'title' => 'Контакты',
                'description' => null,
                'content' => null,
                'active' => true,
                'show_in_menu' => true,
                'menu_order' => 50,
                'menu_label' => 'Контакты',
                'menu_type' => 'anchor',
                'menu_hash' => '#contact',
            ],
            [
                'slug' => 'contacts',
                'title' => 'Контакты — Nexora',
                'description' => 'Контактная информация Nexora: телефон, email, адрес.',
                'content' => [
                    'body' => "Телефон: +375 (29) 123-45-67\nEmail: hello@nexora.by\n\nг. Минск",
                ],
                'active' => true,
                'show_in_menu' => false,
                'show_in_footer' => true,
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 60,
                'footer_label' => 'Контакты',
                'menu_order' => 0,
                'menu_type' => 'route',
                'seo_title' => 'Контакты — Nexora',
                'seo_description' => 'Связаться с Nexora: телефон, email, адрес офиса.',
            ],
        ];

        $footerPages = [
            [
                'slug' => 'about',
                'title' => 'О компании — Nexora',
                'description' => 'О студии Nexora: опыт, команда и подход к разработке.',
                'content' => ['body' => 'Nexora — команда разработчиков, дизайнеров и SEO-специалистов. Мы создаём сайты и веб-приложения под ключ.'],
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 10,
                'footer_label' => 'О нас',
            ],
            [
                'slug' => 'reviews',
                'title' => 'Отзывы — Nexora',
                'description' => 'Отзывы клиентов о работе Nexora.',
                'content' => ['body' => 'Отзывы наших клиентов скоро появятся здесь.'],
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 30,
                'footer_label' => 'Отзывы',
            ],
            [
                'slug' => 'faq',
                'title' => 'Вопрос-ответ — Nexora',
                'description' => 'Частые вопросы о разработке сайтов.',
                'content' => ['body' => 'Раздел вопросов и ответов в разработке.'],
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 40,
                'footer_label' => 'Вопрос-ответ',
            ],
            [
                'slug' => 'blog',
                'title' => 'Блог — Nexora',
                'description' => 'Статьи о веб-разработке и digital.',
                'content' => ['body' => 'Блог скоро будет доступен.'],
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 50,
                'footer_label' => 'Статьи',
            ],
            [
                'slug' => 'sitemap',
                'title' => 'Карта сайта — Nexora',
                'description' => 'Карта сайта Nexora.',
                'content' => ['body' => 'Полный список разделов сайта.'],
                'footer_group' => Page::FOOTER_GROUP_SECTIONS,
                'footer_order' => 70,
                'footer_label' => 'Карта сайта',
            ],
            [
                'slug' => 'services-web',
                'title' => 'Создание сайтов — Nexora',
                'description' => 'Разработка сайтов под ключ.',
                'content' => ['body' => 'Создание корпоративных сайтов, лендингов и порталов на Laravel и других платформах.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 20,
                'footer_label' => 'Создание сайтов',
            ],
            [
                'slug' => 'services-mobile',
                'title' => 'Мобильные приложения — Nexora',
                'description' => 'Разработка мобильных приложений.',
                'content' => ['body' => 'Разработка мобильных приложений для iOS и Android.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 30,
                'footer_label' => 'Мобильные приложения',
            ],
            [
                'slug' => 'services-seo',
                'title' => 'Продвижение сайтов — Nexora',
                'description' => 'SEO и продвижение сайтов.',
                'content' => ['body' => 'Продвижение сайтов в Яндекс и Google, вывод в ТОП поисковой выдачи.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 40,
                'footer_label' => 'Продвижение сайтов',
            ],
            [
                'slug' => 'services-design',
                'title' => 'Дизайн сайтов — Nexora',
                'description' => 'UI/UX дизайн сайтов.',
                'content' => ['body' => 'Проектирование интерфейсов и визуального стиля сайтов.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 50,
                'footer_label' => 'Дизайн сайтов',
            ],
            [
                'slug' => 'services-refactor',
                'title' => 'Доработка сайтов — Nexora',
                'description' => 'Доработка и расширение функционала сайтов.',
                'content' => ['body' => 'Доработка существующих сайтов, новые разделы и интеграции.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 60,
                'footer_label' => 'Доработка сайтов',
            ],
            [
                'slug' => 'services-optimization',
                'title' => 'Оптимизация сайтов — Nexora',
                'description' => 'Оптимизация скорости и SEO сайтов.',
                'content' => ['body' => 'Техническая и SEO-оптимизация для роста скорости и позиций.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 70,
                'footer_label' => 'Оптимизация сайтов',
            ],
            [
                'slug' => 'services-support',
                'title' => 'Поддержка сайтов — Nexora',
                'description' => 'Техническая поддержка сайтов.',
                'content' => ['body' => 'Сопровождение, обновления, резервное копирование и мониторинг.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 80,
                'footer_label' => 'Поддержка сайтов',
            ],
            [
                'slug' => 'services-hosting',
                'title' => 'Хостинг для сайтов — Nexora',
                'description' => 'Хостинг и размещение сайтов.',
                'content' => ['body' => 'Надёжный хостинг для сайтов и веб-приложений.'],
                'footer_group' => Page::FOOTER_GROUP_SERVICES,
                'footer_order' => 90,
                'footer_label' => 'Хостинг для сайтов',
            ],
            [
                'slug' => 'privacy',
                'title' => 'Политика в отношении обработки персональных данных',
                'description' => 'Политика обработки персональных данных Nexora.',
                'content' => ['body' => 'Текст политики обработки персональных данных.'],
                'footer_group' => Page::FOOTER_GROUP_LEGAL,
                'footer_order' => 10,
                'footer_label' => 'Политика в отношении обработки персональных данных',
            ],
            [
                'slug' => 'cookie-policy',
                'title' => 'Политика в отношении использования файлов cookie',
                'description' => 'Политика использования cookie.',
                'content' => ['body' => 'Текст политики использования файлов cookie.'],
                'footer_group' => Page::FOOTER_GROUP_LEGAL,
                'footer_order' => 20,
                'footer_label' => 'Политика в отношении использования файлов cookie',
            ],
            [
                'slug' => 'terms',
                'title' => 'Пользовательское соглашение',
                'description' => 'Пользовательское соглашение Nexora.',
                'content' => ['body' => 'Текст пользовательского соглашения.'],
                'footer_group' => Page::FOOTER_GROUP_LEGAL,
                'footer_order' => 30,
                'footer_label' => 'Пользовательское соглашение',
            ],
        ];

        foreach ($footerPages as $footerPage) {
            $pages[] = array_merge([
                'active' => true,
                'show_in_menu' => false,
                'show_in_footer' => true,
                'menu_order' => 0,
                'menu_type' => 'route',
            ], $footerPage);
        }

        foreach ($pages as $page) {
            Page::query()->updateOrCreate(
                ['slug' => $page['slug']],
                $page
            );
        }
    }
}
